curated_data: "../results/Curated_Data"
raw_data: "../resources/Raw_Data"
gap_lists: "../results/Gap_Lists"
bold_data_dir: "../resources/Raw_Data/BOLD_specieslist_europe"
expert_data_dir: "../resources/Raw_Data/Additional_data_from_experts"
